<?php
/**
 * Created by PhpStorm.
 * User: dami_
 * Date: 4/9/2018
 * Time: 20:47
 */

namespace Modelo;



class Cliente extends Usuario
{
    private $id;
    protected $nombre;
    protected $apellido;
    protected $dni;

    function __construct($nombre, $apellido, $dni, $email, $password)
    {
        parent::__construct($email,$password);
        $this->apellido = $apellido;
        $this->nombre = $nombre;
        $this->dni = $dni;
    }

    function setId($id){
        $this->id=$id;
    }
    function  setIdUsuario($id){
        parent::setId($id);
    }
    function getIdUsuario(){return parent::getId();}
    function getId(){return $this->id;}
    function getNombre(){return $this->nombre;}
    function getApellido(){return $this->apellido;}
    function getDni(){return $this->dni;}
    function getPassword()
    {
        return parent::getPassword(); // TODO: Change the autogenerated stub
    }
    public function getEmail()
    {
        return parent::getEmail(); // TODO: Change the autogenerated stub
    }


}